[build-system]
requires = ["scikit-build-core>=0.10", "numpy>=2.0"]
build-backend = "scikit_build_core.build"

[project]
name = "zvode"
version = "0.1.0"
description = "Python bindings to the classic ZVODE ODE solver"
authors = [{name = "Ivan Pribec", email = "ivan.pribec@gmail.com"}]
requires-python = ">=3.9"
readme = "README.md"
keywords = ["ODE", "solver", "ZVODE", "ODEPACK", "complex", "scientific computing"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Mathematics",
    "License :: OSI Approved :: BSD Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Fortran",
]
dependencies = [
	"numpy>=1.23",
	"scipy>=1.9"
]

[project.urls]
Homepage = "https://github.com/ivan-pi/zvode"
Repository = "https://github.com/ivan-pi/zvode"

[tool.scikit-build]
minimum-version = "build-system.requires"
build.targets = ["_zvode"]
build-dir = "build/{wheel_tag}"   # caches CMake between builds; nice for dev
wheel.packages = ["src/zvode"]
sdist.include = [
    "CMakeLists.txt",
    "extern/**",
    "src/_zvode.c",
    "src/zvode.h",
]