[build-system]
requires = ["scikit-build-core", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "zvode"
version = "0.1.0"
description = "Python bindings to the classic ZVODE ODE solver"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["numpy", "scipy"]

[tool.scikit-build]
#wheel.py-api = "cp38"
cmake.version = "CMakeLists.txt"
build.targets = ["_zvode"]
build-dir = "build/{wheel_tag}"   # caches CMake between builds; nice for dev
wheel.packages = ["src/zvode"]

[tool.scikit-build.cmake.define]
CMAKE_Fortran_COMPILER = "flang"
BLAS_LIBRARIES = "/opt/OpenBLAS/lib/libopenblas.a"
BUILD_TYPE = "Debug"